---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }} 
  labels:
    app: {{ template "name" . }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }} 
  labels:
    app: {{ template "name" . }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }} 
  labels:
    app: {{ template "name" . }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}
  namespace: {{.Release.Namespace}}
